### PR TITLE
Uplift to 1.0.5

### LINKED ISSUE #3: Uplift to 1.0.5 version of API spec
**What version of the API spec does the SDK need to target**

[1.0.5](https://github.com/w-pay/oas-wpay/blob/master/dist/wpay-1-0-5.json)

**Checklist**

- [x] Regenerate Open Api Client
- [x] Upgrade SDK version
- [x] Implement changes
- [x] Add tests (if required) for new functionality
- [x] Bump version of lib
- [x] ~~Publish~~
- [ ] Tag repo

### PR DESCRIPTION
**Pull request by kierans**
Uplift the OpenApi implemenation to 1.0.5 of the Wpay spec.

Fixes #3

### CODE REVIEW

**Comment by kierans** [comment]
@tomabin If you could test this, especially the `CustomerPaymentSessionsRepository.update` to make sure there isn't a regression before this is merge it would be very helpful.

**Comment by tomabin** [comment]
> @tomabin If you could test this, especially the `CustomerPaymentSessionsRepository.update` call to make sure there isn't a regression before this is merge it would be very helpful.

@kierans The first call which we make from the app is to fetchPaymentSession from QRID, the parsing of the response of that call is failing with the current change. It seems to be failing to parse the response to `OAIMeta` model class and is working fine when I removed the meta parameter from the response model but then it failed on the second call which is the updatePaymentSession call which crashes during the conversion of request to model object. I guess this is also related to `OAIMeta`. I modified `OAIMeta` to subclass from `OAIObject` rather than `NSMutableDictionary` and it seems to be working fine and the request is expected as per the updatePaymentSession call. Also, tested the entire payment flow with the change of subclassing from `OAIObject` and is working fine.

**Comment by kierans** [comment]
@tomabin I've added that fix. Thanks for finding the solution 👍

**Review by tomabin — COMMENTED** [review]
Verified the Payment flow with the changes, it's working as expected. Thanks

**Review by tomabin — APPROVED** [review]

**Pull request merged**
